version = 1

[[analyzers]]
  name = "SCA"
  enabled = true

[[analyzers]]
  name = "secret-scanner"
  enabled = true

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "cxx"

[[transformers]]
name = "clang-format"

[[transformers]]
name = "black"

[[transformers]]
name = "isort"

[[transformers]]
name = "ruff"
  [transformers.meta]
  formatter = false
  isort = false
